name: main_commit

on:
  workflow_dispatch: {}
  push: { branches: ['main'] }

jobs:
  test_and_build:
    name: 'Test and build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18
        
      - name: build
        uses: ./.github/actions/build
